export const lang = {
    en: {
        PROFILE: 'Profile',
        FULL_NAME: 'Full Name',
        EMAIL: 'Email',
        EDIT_PROFILE: 'Edit Profile',
        HELP: 'Help',
        CHANGE_PASSWORD: 'Change Password',
        SELECT_APP_LANGUAGE: 'Select app language',
        ENGLISH: 'English',
        SPANISH: 'Spanish',
        LOGOUT_ALL_DEVICES: 'Logout on all devices',
        RECENT_LIKES: 'Recent Likes',
        LOGOUT: 'Logout',
    },
    es: {
        PROFILE: 'Perfil',
        FULL_NAME: 'Nombre Completo',
        EMAIL: 'Correo Electrónico',
        EDIT_PROFILE: 'Editar Perfil',
        HELP: 'Ayuda',
        CHANGE_PASSWORD: 'Cambiar Contraseña',
        SELECT_APP_LANGUAGE: 'Seleccionar lenguaje de la APP',
        ENGLISH: 'Inglés',
        SPANISH: 'Español',
        LOGOUT_ALL_DEVICES: 'Salir en todos los dispositivos',
        RECENT_LIKES: 'Me Gusta más recientes',
        LOGOUT: 'Salir',
    }
};